### ISSUE TITLE
How do I render html tags?

### ISSUE THREAD

**Issue by a5his** [prior/prawnto#9]
If i write below code it displays as it is which is not what I wanted. Doesn't prawnto supports html tags like headers, paragraph, bold, italics, and many more?

pdf.text "<b>a5his</b>"

**Comment by bhauff** [comment]
Prawnto only provides some convenience for using Prawn in Rails.  So the better question is does Prawn support html tags.  The answer to that for the most part is no.  If you are using earlier versions of Prawn with prawn/format you can use bold and italics for sure.  I am not sure what else.  You should check with the Prawn project.

**Comment by a5his** [comment]
I think prawn format can help which lets to pass parameter :inline_format => true
